### ISSUE TITLE
Update a Service

### ISSUE THREAD

**Issue by joshuawilson** [talamer/vscode-knative#27]
# Description
As a user I want to be able to update a knative service.

# Acceptance Criteria 
- It should display the current information and allow the user change it and "save it".

**Comment by joshuawilson** [comment]
There is currently no support for submitting a yaml file back to `kn`, so we can't just edit a yaml in the yaml editor. 

We need to create a form view.

**Comment by gorkem** [comment]
Even if we have to interface `kubectl` instead of `kn` I think it is still better to edit yaml, in the yaml editor. This way we can have a generic enough solution that applies to all kinds of knative resources including eventing ones. 

@markito I think as part of this we should first look at improving the knative YAML editing. Similar to what we did for tekton with code assist, snippets, validation etc.

Form views are expensive things to maintain and knative service update/add is not complicated enough.

**Comment by rhuss** [comment]
(Re-)using YAML editor for creating/update sounds good to me. We added an upstream story for a `kn apply` which is supposed to work also with vanilla yaml (a la `kn apply -f service.yml`). This is supposed to work as an "create-or-update" (like `kubectl apply`).

Longterm there will be UI related meta-data available which is currently also explored for the Web-UI. With this available, forms, can be automatically generated so that the maintenance effort for those forms can be minimised. But this is still some way to go.

**Comment by joshuawilson** [comment]
I've added support `kubectl apply` until we can get `kn apply` available.

**Comment by joshuawilson** [comment]
Added ability to edit yaml files. Currently you can select a Service to display it or select an edit icon and then edit it.
